### ISSUE TITLE
failed to cleanup tracefs

### ISSUE THREAD

**Issue by izzh** [DataDog/ebpf-manager#152]
When I execute `Manager.Start()`, the program throws an error. What could be the reason for this?

```
failed to cleanup tracefs: 6 errors occurred:
	* cannot write "-:p_ext4_file_write_iter_0\n" to kprobe_events: write /sys/kernel/debug/tracing/kprobe_events: device or resource busy
	* cannot write "-:p_ext4_file_read_iter_0\n" to kprobe_events: write /sys/kernel/debug/tracing/kprobe_events: device or resource busy
	* cannot write "-:p_ext4_page_mkwrite_0\n" to kprobe_events: write /sys/kernel/debug/tracing/kprobe_events: device or resource busy
	* cannot write "-:p_filemap_fault_0\n" to kprobe_events: write /sys/kernel/debug/tracing/kprobe_events: device or resource busy
	* cannot write "-:p_xfs_file_write_iter_0\n" to kprobe_events: write /sys/kernel/debug/tracing/kprobe_events: device or resource busy
	* cannot write "-:p_xfs_file_read_iter_0\n" to kprobe_events: write /sys/kernel/debug/tracing/kprobe_events: device or resource busy
```
os: Alibaba Cloud Linux
kernel version: 5.10.134-13.1.al8.x86_64

**Comment by brycekahle** [comment]
Somehow you got programs attached with a PID of `0`, and it is trying to clean those up because it thinks that process is dead.

**Comment by brycekahle** [comment]
Are those eBPF programs yours, or something else on the system?

**Comment by izzh** [comment]
These are not my BPF programs. They might belong to some system software. I intend to ignore this error.
Thank you for your help~

**Comment by brycekahle** [comment]
one way to avoid this error, is to set a short `UID` for all your probes. Then the manager will not attempt to cleanup these programs, because they will be correctly detected as outside the scope of the manager.

**Comment by brycekahle** [comment]
The `UID` can be the same for all the probes, btw.
