### ISSUE TITLE
hook sys_execve fail 

### ISSUE THREAD

**Issue by rockingl** [DataDog/ebpf-manager#55]
hi, i want to use ebpf-manage hook kprobe: sys_execve. (my machine is ubuntu21.04 x86).

when i use this:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/20380742/176172246-8057ad10-66c7-4c1e-aa35-147fc713fc93.png">

error info: {UID:KretprobeSysExecve EBPFSection:kretprobe/sys_execve EBPFFuncName:kretprobe_sys_execve}: symbol 'sys_execve' not found: invalid argument

when i use this:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/20380742/176172391-257073e1-554d-4db4-aa85-930c8c6e2db4.png">

error_info: couldn't find program spec for func kretprobe___x64_sys_execve: unknown section or eBPF function name

i confuse , how to correct use it. i hope someone can help me solve this problem. or tell me correct usage.

thanks!

**Comment by brycekahle** [comment]
`sys_execve` needs to be the name of an actual kernel function. Here is when I check on my VM (M1 arm64):
```
$ grep sys_execve /proc/kallsyms
0000000000000000 T __arm64_compat_sys_execve
0000000000000000 T __arm64_compat_sys_execveat
0000000000000000 T __arm64_sys_execve
0000000000000000 T __arm64_sys_execveat
0000000000000000 t _eil_addr___arm64_compat_sys_execveat
0000000000000000 t _eil_addr___arm64_compat_sys_execve
0000000000000000 t _eil_addr___arm64_sys_execveat
0000000000000000 t _eil_addr___arm64_sys_execve
```
A common pattern is to add `do_` as a prefix, so if you check for `do_execve`, it exists:
```
$ grep do_execve /proc/kallsyms
0000000000000000 t __do_execve_file.isra.0
0000000000000000 T do_execve_file
0000000000000000 T do_execve
0000000000000000 T do_execveat
```
Maybe try that instead?

**Comment by rockingl** [comment]
hi, i run this commands:

run: uname -a
Linux ubuntu 5.11.0-49-generic #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux 

run: grep sys_execve /proc/kallsyms
ffffffff9e32d750 T __ia32_sys_execve
ffffffff9e32d7a0 T __ia32_sys_execveat
ffffffff9e32d810 T __ia32_compat_sys_execve
ffffffff9e32d860 T __ia32_compat_sys_execveat
ffffffff9e32d8d0 T __x32_compat_sys_execveat
ffffffff9e32d940 T __x64_sys_execveat
ffffffff9e32d9b0 T __x64_sys_execve
ffffffff9e32da00 T __x32_compat_sys_execve
ffffffffa03ef170 d _eil_addr___x32_compat_sys_execveat
ffffffffa03ef180 d _eil_addr___ia32_compat_sys_execveat
ffffffffa03ef190 d _eil_addr___x32_compat_sys_execve
ffffffffa03ef1a0 d _eil_addr___ia32_compat_sys_execve
ffffffffa03ef1b0 d _eil_addr___ia32_sys_execveat
ffffffffa03ef1c0 d _eil_addr___x64_sys_execveat
ffffffffa03ef1d0 d _eil_addr___ia32_sys_execve
ffffffffa03ef1e0 d _eil_addr___x64_sys_execve

run: grep do_execve /proc/kallsyms
ffffffff9e32d590 t do_execveat_common

my kern code is:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/20380742/176216714-f1112fa2-d204-47bf-94c8-b8d7ee2ae8ef.png">

my user code is:
<img width="515" alt="image" src="https://user-images.githubusercontent.com/20380742/176216880-5a1b879a-1d04-4c9f-95a3-6cbce6556185.png">

then the error is:
couldn't find program spec for func kretprobe__x64_sys_execve: unknown section or eBPF function name

**Comment by rockingl** [comment]
> `sys_execve` needs to be the name of an actual kernel function. Here is when I check on my VM (M1 arm64):
> 
> ```
> $ grep sys_execve /proc/kallsyms
> 0000000000000000 T __arm64_compat_sys_execve
> 0000000000000000 T __arm64_compat_sys_execveat
> 0000000000000000 T __arm64_sys_execve
> 0000000000000000 T __arm64_sys_execveat
> 0000000000000000 t _eil_addr___arm64_compat_sys_execveat
> 0000000000000000 t _eil_addr___arm64_compat_sys_execve
> 0000000000000000 t _eil_addr___arm64_sys_execveat
> 0000000000000000 t _eil_addr___arm64_sys_execve
> ```
> 
> A common pattern is to add `do_` as a prefix, so if you check for `do_execve`, it exists:
> 
> ```
> $ grep do_execve /proc/kallsyms
> 0000000000000000 t __do_execve_file.isra.0
> 0000000000000000 T do_execve_file
> 0000000000000000 T do_execve
> 0000000000000000 T do_execveat
> ```
> 
> Maybe try that instead?

thanks, but i hav't solve this problem

**Comment by brycekahle** [comment]
Glad you got it working!
