### ISSUE TITLE
use ringbuf fail 

### ISSUE THREAD

**Issue by rockingl** [DataDog/ebpf-manager#56]
hi, i try to use ringbuf. but it load fail.

err: map exec_events: map create without BTF: invalid argument

my env is:

os: ubuntu21.04 
kern: linux 5.11 x86

here is my code:

So, someone can help me? maybe my usages is error. e.g: some params is correctly.

tell me correct usages, if possible. thanks!

**Comment by brycekahle** [comment]
@rockingl I think you forgot to add your code.

**Comment by brycekahle** [comment]
Closing for now. If you add your code, please re-open.
