### ISSUE TITLE
Compare with cilium/ebpf

### ISSUE THREAD

**Issue by yuzhichang** [DataDog/ebpf-manager#57]
I have a question on how it compare to [cilum/ebpf](https://github.com/cilium/ebpf).
[cilum/ebpf](https://github.com/cilium/ebpf) converts a bpf C file into Go file inside a docker container, and the container is independent with the target Linux host kernel. It doesn't require the Clang and kernel headers be installed on the dev machine.
`DataDog/ebpf-manager` is based on [cilum/ebpf](https://github.com/cilium/ebpf) but requires the Clang and kernel headers be installed on the dev machine.
I'm confused what's the value this project? Correct me if I'm wrong. Thanks!

**Comment by yuzhichang** [comment]
@brycekahle Is it possible to not requiring Clang and headers on dev machine like `cilum/ebpf`?

**Comment by brycekahle** [comment]
@yuzhichang That is only for the examples, you don't need it for using the library.

**Comment by yuzhichang** [comment]
Thanks for your reply.
